### ISSUE TITLE
Installation Dependency Issue

### ISSUE THREAD

**Issue by a-attia** [dgursoy/coho#10]
There seems some incompatibility.
Coho is installed, and all packages seem to be installed. Though, when I try to run/load things (in this case, I installed ipython and tried loading coho), I get the following error:
NOTE: the paths to `__init__` are masked here...

```
In [1]: import coho
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import coho

File ~~~~/coho/coho/__init__.py:35
      3 """
      4 Toolkit for wavefront propagation simulations.
      5
   (...)
     31         interactor: Interaction definitions
     32 """
     34 # Configuration
---> 35 from .config import *
     37 # Factories
     38 from .factories.simulation_factories import *

File ~~~~/coho/coho/config/__init__.py:22
      1 # config/__init__.py
      3 """Configuration management.
      4
      5 This package provides a complete configuration system for optical simulations,
   (...)
     19     models: Pydantic models for configuration objects
     20 """
---> 22 from .loader import load_config
     23 from .reader import read_config
     25 __all__ = [
     26     'load_config',
     27     'read_config',
     28 ]

File ~~~~/coho/coho/config/loader.py:12
      9 from pathlib import Path
     10 from typing import Union, Dict, Any
---> 12 from .reader import read_config
     13 from .schemas import register_schemas
     14 from .validator import validate_config

File ~~~~/coho/coho/config/reader.py:19
     17 from os import PathLike
     18 from pathlib import Path
---> 19 import yaml
     20 import json
     21 import tomli

ModuleNotFoundError: No module named 'yaml'

```

**Comment by a-attia** [comment]
FYI: the `yaml` package is already installed but it seems undiscoverable which might indicate version incompatibility.
- My python version is `3.12.7`.
Trying to update `pyyaml` results in:
```Requirement already satisfied: pyyaml in ./venv/lib/python3.12/site-packages (6.0.2)```

**Comment by dgursoy** [comment]
It looks like you're using an IPython instance that isn’t part of your Poetry-managed virtual environment. To resolve this, you need to add IPython to your environment. Make sure you're at the project root (where the pyproject.toml file is located), and run:

```bash
poetry add ipython
```

Once installed, you can start IPython within the virtual environment using:

```bash
poetry run ipython
```

If you prefer to avoid prefixing commands with `poetry run` every time, you can activate the virtual environment (again at project root) with:

```bash
poetry shell
```

This will drop you into a shell where the virtual environment is active, allowing you to run commands like `ipython` directly without the need for `poetry run`.

To deactivate the Poetry shell, simply exit the virtual environment by running:

```bash
exit
```

**Comment by a-attia** [comment]
OK; I see the problem. 
I was basically mixing `python venv`, `poetry` and `pip`. 
It is weird thought that simply `pip install -e .` results in this error!

**Comment by a-attia** [comment]
Just note that the `pip` installation instructions below is what I initially followed to the letter and caused this (after installing ipython with pip):


For an isolated environment (recommended), use:
```
# Create a new virtual environment named 'mycoho'
python -m venv mycoho

# Activate the virtual environment
source venv/bin/activate

# Install Coho in the virtual environment
pip install coho
```

**Comment by a-attia** [comment]
With some investigation (as I am very newbie to poetry), it seems using pip or brew to install and/or manage poetry is not recommended. The [poetry site](https://python-poetry.org/docs/) seem to recommend using `pipx`

See:
- https://stackoverflow.com/questions/73365780/why-is-not-recommended-to-install-poetry-with-homebrew

**Comment by a-attia** [comment]
OK, here is my summary:
Your instructions on using poetry to add and run/manage ipython work just fine. Though, it is a bit annoying (only a personal preference). 
So, problem solved. I am moving on.
